# -*- coding: utf-8 -*-
"""Proyek Analisis Data Dicoding_KA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XzNnPJOsWTCxrB9Ef_BhHHOyXW9_h1r

# Proyek Analisis Data: Bike Sharing Dataset
- **Nama:** kamilatul aini
- **Email:** kamilatulaini8@gmail.com
- **ID Dicoding:** kamilatul

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Pada jam berapa jumlah sharing sepeda terbanyak?
- Pertanyaan 2 : Apakah jumlah sharing sepeda per tahun mengalami kenaikan?

## Import Semua Packages/Library yang Digunakan
"""

import streamlit as st
import streamlit.components.v1 as stc
import pandas as pd
import numpy as numpy
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

"""## Data Wrangling

### Gathering Data
"""

import pandas as pd

df = pd.read_csv('/content/hour.csv')

print(df.head())  # Untuk melihat beberapa baris pertama dari dataset

"""**Insight:**
- Dapat dilihat bahwa dataset bike sharing ini memiliki 2 data berformat csv, yang pertama day.csv dan hour.csv. Untuk kali ini kita menggunakan hour.csv agar bisa diekplorasi lebih sampai ke data per jam nya
- Dapat dilihat juga bahwa data tidak ada yang null/N.A/sejenis nya

### Assessing Data
"""

# Memeriksa tipe data dan jumlah nilai kosong
print(df.info())
print(df.isnull().sum())

"""**Insight:**
- Dapat dilihat bahwa data aman dan tidak terindikasi NULL
- Dan data juga tidak ada yang kosong

### Cleaning Data
"""

# Memeriksa apakah ada data yang duplikat
print(df.duplicated().sum())

"""**Insight:**
- Diperoleh output "0" membuktikan bahwa tidak ada ditemukan data duplikasi

## Exploratory Data Analysis (EDA)

### Explore ...
"""

print(df.describe())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
# Select only numeric columns for correlation calculation
numeric_df = df.select_dtypes(include='number')
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Korelasi Antar Variabel Numerik") # Update title to reflect only numeric variables
plt.show()

"""**Insight:**
- Terlihat bahwa korelasi antar variabel kuat dan positif, seperti: korelasi varibael temp dan atemp memiliki korelasi positif yang sangat kuat
- Ditemukan juga bahwa adanya korelasi yang lemah atau negatif, seperti: korelasi variabel hum dan windspeed

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Visualisasi jumlah peminjaman per jam
plt.figure(figsize=(12, 6))
sns.barplot(x=df['hr'], y=df['cnt'], color='skyblue')

plt.xlabel("Jam dalam Sehari (0-23)")
plt.ylabel("Jumlah Peminjaman Sepeda")
plt.title("Jumlah Peminjaman Sepeda per Jam")
plt.xticks(range(0, 24))  # Menampilkan semua label jam (0-23)
plt.grid(axis='y', linestyle='--', alpha=0.7)  # Menambahkan grid horizontal
plt.tight_layout()

# Menampilkan plot
plt.show()

"""**Insight**
- Dapat diperoleh bahwa peak hour untuk sharing sepeda berada di pukul 8 pagi dan 5 sore
- Untuk di jam terendah berada di pukul 0 - 5 dinihari

### Pertanyaan 2:
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Konversi kolom 'dteday' ke datetime
df['dteday'] = pd.to_datetime(df['dteday'], errors='coerce')

# Hitung total peminjaman per tahun
yearly_rentals = df.groupby(df['dteday'].dt.year)['cnt'].sum().reset_index()

# Visualisasi
plt.figure(figsize=(10, 6))
ax = sns.barplot(x='dteday', y='cnt', data=yearly_rentals, color='skyblue')

# Menambahkan label di setiap batang
for bar in ax.containers:
    ax.bar_label(bar, fmt='%d', fontsize=12, padding=3)

plt.xlabel("Tahun")
plt.ylabel("Total Peminjaman Sepeda")
plt.title("Tren Peminjaman Sepeda per Tahun")
plt.show()

"""**Insight:**
- Dapat dilihat dari output diatas, untuk peminjaman sepeda tahun 2011 mencapai hampir 1,25 Juta dan untuk 2012 mencapai lebih dari 2 Juta.
- Ini menunjukkan bahwa setiap tahun mengalami peningkatan yang signifikan

## Analisis Lanjutan (Opsional)

## Conclusion

- Peak hour didapat pada pagi dan sore hari, ini berarti kegiatan penyewaan sepeda sangat ramai di jam 8 pagi sampai 5 sore
- Peminjaman sepeda mengalami kenaikan yang signifikan positif
"""